# Generated by Django 5.1.7 on 2025-03-28 22:09

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("node_id", models.IntegerField(default=0)),
                ("temperature", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
