services:
  redis:
    image: redis:latest
    ports:
      - 6555:6379
    volumes:
      - redis_data:/data

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    env_file:
      - .env.db
    ports:
      - 5555:5432 # localhost:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  timescale_data:
