services:
  redis:
    networks: 
      - edge
    image: redis:latest
    ports:
      - 6555:6379
    volumes:
      - redis_data:/data

  timescaledb:
    networks:
      - edge
    image: timescale/timescaledb:latest-pg16
    env_file:
      - .env.db
    ports:
      - 5555:5432 # localhost:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    networks:
      - edge
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: src
          target: /code
        - action: sync+restart
          path: ./requirements.txt
          target: /tmp/requirements.txt
            
    environment:
      - NODE_ID=0
      - PORT=8088
    env_file:
      - .env.web-container
    ports:
      - 8088:8088

volumes:
  redis_data:
  timescale_data:

networks:
  edge:
